Repository sonata-project/sonata-doctrine-extensions, pull requests merged in 2022-07, with the labels that each got.

#426 DevKit updates for 1.x branch
  .github/workflows/test.yaml
  .php-cs-fixer.dist.php
  composer.json
  phpstan-baseline.neon
  src/Test/EntityManagerMockFactoryTrait.php
Labels: minor

#428 Update rector
  composer.json
Labels: pedantic

#429 Remove EntityManagerMockFactoryTrait
  src/Test/EntityManagerMockFactoryTrait.php
Labels: major
