Repository sonata-project/sonata-doctrine-extensions, pull requests merged in 2022-05, with the labels that each got.

#408 Deprecate PHPCR
  .github/workflows/test.yaml
  composer.json
  phpstan-baseline.neon
  phpstan.neon.dist
  psalm-baseline.xml
  src/Adapter/PHPCR/DoctrinePHPCRAdapter.php
  src/Bridge/Symfony/DependencyInjection/Compiler/AdapterCompilerPass.php
  src/Bridge/Symfony/DependencyInjection/SonataDoctrineExtension.php
  src/Document/BasePHPCRManager.php
  src/Mapper/ORM/DoctrineORMMapper.php
  tests/Adapter/PHPCR/DoctrinePHPCRAdapterTest.php
  tests/Bridge/Symfony/DependencyInjection/SonataDoctrineExtensionTest.php
Labels: minor

#412 Add support for `doctrine/persistence` 3
  composer.json
  src/Model/BaseManager.php
  src/Model/ClearableManagerInterface.php
Labels: minor

#414 Add rector
  .github/workflows/qa.yaml
  Makefile
  composer.json
  rector.php
  src/Mapper/Builder/ColumnDefinitionBuilder.php
  src/Mapper/Builder/OptionsBuilder.php
  src/Mapper/DoctrineCollector.php
  src/Mapper/ORM/DoctrineORMMapper.php
  src/Types/JsonType.php
  tests/Model/BaseManagerTest.php
Labels: pedantic

#420 Remove deprecated code
  UPGRADE-2.0.md
  phpstan-baseline.neon
  phpstan.neon.dist
  psalm-baseline.xml
  psalm.xml
  src/Adapter/AdapterChain.php
  src/Adapter/AdapterInterface.php
  src/Adapter/ORM/DoctrineORMAdapter.php
  src/Adapter/PHPCR/DoctrinePHPCRAdapter.php
  src/Bridge/Symfony/Bundle/SonataDoctrineBundle.php
  src/Bridge/Symfony/DependencyInjection/Compiler/AdapterCompilerPass.php
  src/Bridge/Symfony/DependencyInjection/SonataDoctrineExtension.php
  src/Bridge/Symfony/Resources/config/doctrine_phpcr.php
  src/Bridge/Symfony/SonataDoctrineBundle.php
  src/Bridge/Symfony/SonataDoctrineSymfonyBundle.php
  src/Document/BaseDocumentManager.php
  src/Document/BasePHPCRManager.php
  src/Entity/BaseEntityManager.php
  src/Mapper/Builder/ColumnDefinitionBuilder.php
  src/Mapper/Builder/OptionsBuilder.php
  src/Mapper/DoctrineCollector.php
  src/Mapper/ORM/DoctrineORMMapper.php
  src/Model/BaseManager.php
  src/Model/ClearableManagerInterface.php
  src/Model/ManagerInterface.php
  src/Model/PageableManagerInterface.php
  src/Test/EntityManagerMockFactory.php
  src/Types/JsonType.php
  tests/Adapter/ORM/DoctrineORMAdapterTest.php
  tests/Adapter/PHPCR/DoctrinePHPCRAdapterTest.php
  tests/Bridge/Symfony/DependencyInjection/Compiler/AdapterCompilerPassTest.php
  tests/Bridge/Symfony/DependencyInjection/SonataDoctrineExtensionTest.php
  tests/Entity/BaseEntityManagerTest.php
  tests/Mapper/Builder/OptionsBuilderTest.php
  tests/Mapper/DoctrineCollectorTest.php
  tests/Mapper/ORM/DoctrineORMMapperTest.php
  tests/Types/JsonTypeTest.php
Labels: major

#423 Make getObjectManager protected
  src/Model/BaseManager.php
  tests/Entity/BaseEntityManagerTest.php
Labels: major

#424 Drop support of Symfony 5.3
  composer.json
Labels: minor
