Repository sonata-project/sonata-doctrine-extensions, pull requests merged in 2024-06, with the labels that each got.

#509 Bump rector
  composer.json
Labels: pedantic

#510 DevKit updates for 2.x branch
  .github/workflows/lint.yaml
  .github/workflows/qa.yaml
  .github/workflows/test.yaml
  psalm.xml
Labels: automerge, dev-kit

#511 Solve internal class usage
  src/Bridge/Symfony/DependencyInjection/SonataDoctrineExtension.php
Labels: patch
